### ISSUE TITLE
yomitan kickoff [tracking issue]

### ISSUE THREAD

**Issue by djahandarie** [themoeway/yomitan#2]
Initial steps:
- [x] Configure repo settings
- [x] Update README.md. #1 
- [x] #4
- [x] Set up [issue labels](https://github.com/themoeway/yomitan/labels)
- [ ] #84
