### ISSUE TITLE
Import issues using kamino

### ISSUE THREAD

**Issue by djahandarie** [themoeway/yomitan#4]
kamino needs a couple modifications to be able to cleanly import all the issues from yomichan.

- [x] https://github.com/gatewayapps/kamino/pull/188
- [x] https://github.com/gatewayapps/kamino/pull/189
- [x] https://github.com/gatewayapps/kamino/pull/190
- [x] https://github.com/gatewayapps/kamino/pull/191
- [x] https://github.com/gatewayapps/kamino/pull/192
- [x] https://github.com/gatewayapps/kamino/pull/193

And finally:
- [ ] Import issues [In progress but the import account got flagged and I'm currently waiting on a GitHub support ticket for it to be unflagged]

**Comment by Kuuuube** [comment]
Closing this as it doesn't seem to be necessary to complete this anymore.
